use super::*;

pub(super) fn emit_array_helpers(out: &mut String, element_type: &ValueType) {
    let array = c_array_ident(element_type);
    let option = c_enum_ident("Option", &[element_type.clone()]);
    let some = c_enum_variant_ident("Option", &[element_type.clone()], "Some");
    let none = c_enum_variant_ident("Option", &[element_type.clone()], "None");
    out.push_str("static ");
    out.push_str(&array);
    out.push(' ');
    out.push_str(&array);
    out.push_str("_new(void) {\n");
    out.push_str("    return (");
    out.push_str(&array);
    out.push_str("){.len = 0, .cap = 0, .data = NULL, .refcount = NULL};\n");
    out.push_str("}\n\n");
    out.push_str("static ");
    out.push_str(&array);
    out.push(' ');
    out.push_str(&array);
    out.push_str("_retain(");
    out.push_str(&array);
    out.push_str(" array) {\n");
    out.push_str("    if (array.refcount != NULL) { *array.refcount += 1; }\n");
    out.push_str("    return array;\n");
    out.push_str("}\n\n");
    out.push_str("static ");
    out.push_str("void ");
    out.push_str(&array);
    out.push_str("_release(");
    out.push_str(&array);
    out.push_str(" array) {\n");
    out.push_str("    if (array.refcount == NULL) { return; }\n");
    out.push_str("    *array.refcount -= 1;\n");
    out.push_str("    if (*array.refcount != 0) { return; }\n");
    emit_array_element_release_loop(out, element_type);
    out.push_str("    free(array.data);\n");
    out.push_str("    free(array.refcount);\n");
    out.push_str("}\n\n");
    out.push_str("static ");
    out.push_str(&array);
    out.push(' ');
    out.push_str(&array);
    out.push_str("_make_unique(");
    out.push_str(&array);
    out.push_str(" array, size_t needed) {\n");
    out.push_str("    size_t cap = array.cap;\n");
    out.push_str("    if (cap < needed) { cap = cap == 0 ? 4 : cap; }\n");
    out.push_str("    while (cap < needed) { cap *= 2; }\n");
    out.push_str("    if (cap == 0) { return array; }\n");
    out.push_str("    if (array.refcount != NULL && *array.refcount == 1 && array.cap >= needed) { return array; }\n");
    out.push_str("    ");
    out.push_str(&c_type(element_type));
    out.push_str(" *data = (");
    out.push_str(&c_type(element_type));
    out.push_str(" *)malloc(cap * sizeof(");
    out.push_str(&c_type(element_type));
    out.push_str("));\n");
    out.push_str("    if (data == NULL) { nomo_panic(\"out of memory\"); }\n");
    out.push_str("    for (size_t i = 0; i < array.len; i += 1) { data[i] = ");
    emit_array_element_retain_expr(out, element_type, "array.data[i]");
    out.push_str("; }\n");
    out.push_str("    size_t *refcount = (size_t *)malloc(sizeof(size_t));\n");
    out.push_str("    if (refcount == NULL) { nomo_panic(\"out of memory\"); }\n");
    out.push_str("    *refcount = 1;\n");
    out.push_str("    ");
    out.push_str(&array);
    out.push_str("_release(array);\n");
    out.push_str("    array.data = data;\n");
    out.push_str("    array.cap = cap;\n");
    out.push_str("    array.refcount = refcount;\n");
    out.push_str("    return array;\n");
    out.push_str("}\n\n");
    out.push_str("static ");
    out.push_str(&array);
    out.push(' ');
    out.push_str(&array);
    out.push_str("_push(");
    out.push_str(&array);
    out.push_str(" array, ");
    out.push_str(&c_type(element_type));
    out.push_str(" value) {\n");
    out.push_str("    array = ");
    out.push_str(&array);
    out.push_str("_make_unique(array, array.len + 1);\n");
    out.push_str("    array.data[array.len] = ");
    emit_array_element_retain_expr(out, element_type, "value");
    out.push_str(";\n");
    out.push_str("    array.len += 1;\n");
    out.push_str("    return array;\n");
    out.push_str("}\n\n");
    out.push_str("static ");
    out.push_str(&array);
    out.push(' ');
    out.push_str(&array);
    out.push_str("_insert(");
    out.push_str(&array);
    out.push_str(" array, uint64_t index, ");
    out.push_str(&c_type(element_type));
    out.push_str(" value) {\n");
    out.push_str(
        "    if (index > array.len) { nomo_panic(\"Array.insert index out of bounds\"); }\n",
    );
    out.push_str("    array = ");
    out.push_str(&array);
    out.push_str("_make_unique(array, array.len + 1);\n");
    out.push_str("    size_t insert_index = (size_t)index;\n");
    out.push_str("    for (size_t i = array.len; i > insert_index; i -= 1) { array.data[i] = array.data[i - 1]; }\n");
    out.push_str("    array.data[insert_index] = ");
    emit_array_element_retain_expr(out, element_type, "value");
    out.push_str(";\n");
    out.push_str("    array.len += 1;\n");
    out.push_str("    return array;\n");
    out.push_str("}\n\n");
    out.push_str("static ");
    out.push_str(&array);
    out.push(' ');
    out.push_str(&array);
    out.push_str("_clear(");
    out.push_str(&array);
    out.push_str(" array) {\n");
    out.push_str("    array = ");
    out.push_str(&array);
    out.push_str("_make_unique(array, array.len);\n");
    emit_array_element_release_loop(out, element_type);
    out.push_str("    array.len = 0;\n");
    out.push_str("    return array;\n");
    out.push_str("}\n\n");
    out.push_str("static ");
    out.push_str(&option);
    out.push(' ');
    out.push_str(&array);
    out.push_str("_pop(");
    out.push_str(&array);
    out.push_str(" *array) {\n");
    out.push_str("    if (array->len == 0) {\n");
    out.push_str("        return (");
    out.push_str(&option);
    out.push_str("){.tag = ");
    out.push_str(&none);
    out.push_str("};\n");
    out.push_str("    }\n");
    out.push_str("    *array = ");
    out.push_str(&array);
    out.push_str("_make_unique(*array, array->len);\n");
    out.push_str("    size_t index = array->len - 1;\n");
    out.push_str("    ");
    out.push_str(&c_type(element_type));
    out.push_str(" value = ");
    emit_array_element_retain_expr(out, element_type, "array->data[index]");
    out.push_str(";\n");
    emit_array_element_release_stmt(out, element_type, "array->data[index]");
    out.push_str("    array->len -= 1;\n");
    out.push_str("    return (");
    out.push_str(&option);
    out.push_str("){.tag = ");
    out.push_str(&some);
    out.push_str(", .payload.");
    out.push_str(&c_payload_ident("Some"));
    out.push_str(" = value};\n");
    out.push_str("}\n\n");
    out.push_str("static ");
    out.push_str(&option);
    out.push(' ');
    out.push_str(&array);
    out.push_str("_remove(");
    out.push_str(&array);
    out.push_str(" *array, uint64_t index) {\n");
    out.push_str("    if (index >= array->len) {\n");
    out.push_str("        return (");
    out.push_str(&option);
    out.push_str("){.tag = ");
    out.push_str(&none);
    out.push_str("};\n");
    out.push_str("    }\n");
    out.push_str("    *array = ");
    out.push_str(&array);
    out.push_str("_make_unique(*array, array->len);\n");
    out.push_str("    size_t remove_index = (size_t)index;\n");
    out.push_str("    ");
    out.push_str(&c_type(element_type));
    out.push_str(" value = ");
    emit_array_element_retain_expr(out, element_type, "array->data[remove_index]");
    out.push_str(";\n");
    emit_array_element_release_stmt(out, element_type, "array->data[remove_index]");
    out.push_str("    for (size_t i = remove_index; i + 1 < array->len; i += 1) { array->data[i] = array->data[i + 1]; }\n");
    out.push_str("    array->len -= 1;\n");
    out.push_str("    return (");
    out.push_str(&option);
    out.push_str("){.tag = ");
    out.push_str(&some);
    out.push_str(", .payload.");
    out.push_str(&c_payload_ident("Some"));
    out.push_str(" = value};\n");
    out.push_str("}\n\n");
    out.push_str("static ");
    out.push_str(&option);
    out.push(' ');
    out.push_str(&array);
    out.push_str("_get(");
    out.push_str(&array);
    out.push_str(" array, uint64_t index) {\n");
    out.push_str("    if (index >= array.len) {\n");
    out.push_str("        return (");
    out.push_str(&option);
    out.push_str("){.tag = ");
    out.push_str(&none);
    out.push_str("};\n");
    out.push_str("    }\n");
    out.push_str("    return (");
    out.push_str(&option);
    out.push_str("){.tag = ");
    out.push_str(&some);
    out.push_str(", .payload.");
    out.push_str(&c_payload_ident("Some"));
    out.push_str(" = ");
    emit_array_element_retain_expr(out, element_type, "array.data[index]");
    out.push_str("};\n");
    out.push_str("}\n\n");
    out.push_str("static ");
    out.push_str(&array);
    out.push(' ');
    out.push_str(&array);
    out.push_str("_set(");
    out.push_str(&array);
    out.push_str(" array, uint64_t index, ");
    out.push_str(&c_type(element_type));
    out.push_str(" value) {\n");
    out.push_str(
        "    if (index >= array.len) { nomo_panic(\"Array.set index out of bounds\"); }\n",
    );
    out.push_str("    array = ");
    out.push_str(&array);
    out.push_str("_make_unique(array, array.len);\n");
    emit_array_element_release_stmt(out, element_type, "array.data[index]");
    out.push_str("    array.data[index] = ");
    emit_array_element_retain_expr(out, element_type, "value");
    out.push_str(";\n");
    out.push_str("    return array;\n");
    out.push_str("}\n");
}

pub(super) fn emit_string_split_helper(out: &mut String) {
    let array = c_array_ident(&ValueType::String);
    out.push_str("static ");
    out.push_str(&array);
    out.push_str(" nomo_string_split(nomo_string value, nomo_string separator) {\n");
    out.push_str("    size_t separator_len = strlen(separator.data);\n");
    out.push_str("    if (separator_len == 0) { nomo_panic(\"string.split separator must not be empty\"); }\n");
    out.push_str("    const char *data = value.data;\n");
    out.push_str("    size_t data_len = strlen(data);\n");
    out.push_str("    size_t start = 0;\n");
    out.push_str("    ");
    out.push_str(&array);
    out.push_str(" parts = ");
    out.push_str(&array);
    out.push_str("_new();\n");
    out.push_str("    while (start <= data_len) {\n");
    out.push_str("        const char *found = strstr(data + start, separator.data);\n");
    out.push_str("        size_t segment_len = found == NULL ? data_len - start : (size_t)(found - (data + start));\n");
    out.push_str(
        "        nomo_string segment = nomo_string_from_slice(data, start, segment_len);\n",
    );
    out.push_str("        parts = ");
    out.push_str(&array);
    out.push_str("_push(parts, segment);\n");
    out.push_str("        nomo_string_release(segment);\n");
    out.push_str("        if (found == NULL) { break; }\n");
    out.push_str("        start = (size_t)(found - data) + separator_len;\n");
    out.push_str("    }\n");
    out.push_str("    return parts;\n");
    out.push_str("}\n");
}

pub(super) fn emit_collections_helpers(out: &mut String) {
    let string_array = c_array_ident(&ValueType::String);
    let map_type = ValueType::Struct("StringMap".to_string(), Vec::new());
    let set_type = ValueType::Struct("StringSet".to_string(), Vec::new());
    let map = c_type(&map_type);
    let set = c_type(&set_type);
    let option_string = c_enum_ident("Option", &[ValueType::String]);
    let option_some = c_enum_variant_ident("Option", &[ValueType::String], "Some");
    let option_none = c_enum_variant_ident("Option", &[ValueType::String], "None");
    let keys = c_member_ident("keys");
    let values = c_member_ident("values");
    let payload_some = c_payload_ident("Some");

    out.push_str("static ");
    out.push_str(&map);
    out.push_str(" nomo_collections_map_new(void) {\n");
    out.push_str("    return (");
    out.push_str(&map);
    out.push_str("){.");
    out.push_str(&keys);
    out.push_str(" = ");
    out.push_str(&string_array);
    out.push_str("_new(), .");
    out.push_str(&values);
    out.push_str(" = ");
    out.push_str(&string_array);
    out.push_str("_new()};\n");
    out.push_str("}\n\n");

    out.push_str("static uint64_t nomo_collections_map_len(");
    out.push_str(&map);
    out.push_str(" map) {\n");
    out.push_str("    return (uint64_t)map.");
    out.push_str(&keys);
    out.push_str(".len;\n");
    out.push_str("}\n\n");

    out.push_str("static ");
    out.push_str(&option_string);
    out.push_str(" nomo_collections_map_get(");
    out.push_str(&map);
    out.push_str(" map, nomo_string key) {\n");
    out.push_str("    for (size_t i = 0; i < map.");
    out.push_str(&keys);
    out.push_str(".len; i += 1) {\n");
    out.push_str("        if (nomo_string_equal(map.");
    out.push_str(&keys);
    out.push_str(".data[i], key)) {\n");
    out.push_str("            return (");
    out.push_str(&option_string);
    out.push_str("){.tag = ");
    out.push_str(&option_some);
    out.push_str(", .payload.");
    out.push_str(&payload_some);
    out.push_str(" = nomo_string_retain(map.");
    out.push_str(&values);
    out.push_str(".data[i])};\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("    return (");
    out.push_str(&option_string);
    out.push_str("){.tag = ");
    out.push_str(&option_none);
    out.push_str("};\n");
    out.push_str("}\n\n");

    out.push_str("static int nomo_collections_map_contains(");
    out.push_str(&map);
    out.push_str(" map, nomo_string key) {\n");
    out.push_str("    for (size_t i = 0; i < map.");
    out.push_str(&keys);
    out.push_str(".len; i += 1) {\n");
    out.push_str("        if (nomo_string_equal(map.");
    out.push_str(&keys);
    out.push_str(".data[i], key)) { return 1; }\n");
    out.push_str("    }\n");
    out.push_str("    return 0;\n");
    out.push_str("}\n\n");

    out.push_str("static ");
    out.push_str(&map);
    out.push_str(" nomo_collections_map_set(");
    out.push_str(&map);
    out.push_str(" map, nomo_string key, nomo_string value) {\n");
    out.push_str("    map = ");
    out.push_str(&c_retain_ident(&map_type));
    out.push_str("(map);\n");
    out.push_str("    for (size_t i = 0; i < map.");
    out.push_str(&keys);
    out.push_str(".len; i += 1) {\n");
    out.push_str("        if (nomo_string_equal(map.");
    out.push_str(&keys);
    out.push_str(".data[i], key)) {\n");
    out.push_str("            map.");
    out.push_str(&values);
    out.push_str(" = ");
    out.push_str(&string_array);
    out.push_str("_set(map.");
    out.push_str(&values);
    out.push_str(", (uint64_t)i, value);\n");
    out.push_str("            return map;\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("    map.");
    out.push_str(&keys);
    out.push_str(" = ");
    out.push_str(&string_array);
    out.push_str("_push(map.");
    out.push_str(&keys);
    out.push_str(", key);\n");
    out.push_str("    map.");
    out.push_str(&values);
    out.push_str(" = ");
    out.push_str(&string_array);
    out.push_str("_push(map.");
    out.push_str(&values);
    out.push_str(", value);\n");
    out.push_str("    return map;\n");
    out.push_str("}\n\n");

    out.push_str("static ");
    out.push_str(&map);
    out.push_str(" nomo_collections_map_remove(");
    out.push_str(&map);
    out.push_str(" map, nomo_string key) {\n");
    out.push_str("    map = ");
    out.push_str(&c_retain_ident(&map_type));
    out.push_str("(map);\n");
    out.push_str("    for (size_t i = 0; i < map.");
    out.push_str(&keys);
    out.push_str(".len; i += 1) {\n");
    out.push_str("        if (nomo_string_equal(map.");
    out.push_str(&keys);
    out.push_str(".data[i], key)) {\n");
    out.push_str("            ");
    out.push_str(&option_string);
    out.push_str(" removed_key = ");
    out.push_str(&string_array);
    out.push_str("_remove(&map.");
    out.push_str(&keys);
    out.push_str(", (uint64_t)i);\n");
    out.push_str("            ");
    out.push_str(&option_string);
    out.push_str(" removed_value = ");
    out.push_str(&string_array);
    out.push_str("_remove(&map.");
    out.push_str(&values);
    out.push_str(", (uint64_t)i);\n");
    out.push_str("            ");
    out.push_str(&option_string);
    out.push_str("_release(removed_key);\n");
    out.push_str("            ");
    out.push_str(&option_string);
    out.push_str("_release(removed_value);\n");
    out.push_str("            return map;\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("    return map;\n");
    out.push_str("}\n\n");

    out.push_str("static ");
    out.push_str(&set);
    out.push_str(" nomo_collections_set_new(void) {\n");
    out.push_str("    return (");
    out.push_str(&set);
    out.push_str("){.");
    out.push_str(&values);
    out.push_str(" = ");
    out.push_str(&string_array);
    out.push_str("_new()};\n");
    out.push_str("}\n\n");

    out.push_str("static uint64_t nomo_collections_set_len(");
    out.push_str(&set);
    out.push_str(" set) {\n");
    out.push_str("    return (uint64_t)set.");
    out.push_str(&values);
    out.push_str(".len;\n");
    out.push_str("}\n\n");

    out.push_str("static int nomo_collections_set_contains(");
    out.push_str(&set);
    out.push_str(" set, nomo_string value) {\n");
    out.push_str("    for (size_t i = 0; i < set.");
    out.push_str(&values);
    out.push_str(".len; i += 1) {\n");
    out.push_str("        if (nomo_string_equal(set.");
    out.push_str(&values);
    out.push_str(".data[i], value)) { return 1; }\n");
    out.push_str("    }\n");
    out.push_str("    return 0;\n");
    out.push_str("}\n\n");

    out.push_str("static ");
    out.push_str(&set);
    out.push_str(" nomo_collections_set_insert(");
    out.push_str(&set);
    out.push_str(" set, nomo_string value) {\n");
    out.push_str("    set = ");
    out.push_str(&c_retain_ident(&set_type));
    out.push_str("(set);\n");
    out.push_str("    if (!nomo_collections_set_contains(set, value)) {\n");
    out.push_str("        set.");
    out.push_str(&values);
    out.push_str(" = ");
    out.push_str(&string_array);
    out.push_str("_push(set.");
    out.push_str(&values);
    out.push_str(", value);\n");
    out.push_str("    }\n");
    out.push_str("    return set;\n");
    out.push_str("}\n\n");

    out.push_str("static ");
    out.push_str(&set);
    out.push_str(" nomo_collections_set_remove(");
    out.push_str(&set);
    out.push_str(" set, nomo_string value) {\n");
    out.push_str("    set = ");
    out.push_str(&c_retain_ident(&set_type));
    out.push_str("(set);\n");
    out.push_str("    for (size_t i = 0; i < set.");
    out.push_str(&values);
    out.push_str(".len; i += 1) {\n");
    out.push_str("        if (nomo_string_equal(set.");
    out.push_str(&values);
    out.push_str(".data[i], value)) {\n");
    out.push_str("            ");
    out.push_str(&option_string);
    out.push_str(" removed = ");
    out.push_str(&string_array);
    out.push_str("_remove(&set.");
    out.push_str(&values);
    out.push_str(", (uint64_t)i);\n");
    out.push_str("            ");
    out.push_str(&option_string);
    out.push_str("_release(removed);\n");
    out.push_str("            return set;\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("    return set;\n");
    out.push_str("}\n");
}

fn emit_array_element_release_loop(out: &mut String, element_type: &ValueType) {
    if value_type_needs_release(element_type) {
        out.push_str("    for (size_t i = 0; i < array.len; i += 1) { ");
        emit_array_element_release_expr(out, element_type, "array.data[i]");
        out.push_str("; }\n");
    }
}

fn emit_array_element_release_stmt(out: &mut String, element_type: &ValueType, value: &str) {
    if value_type_needs_release(element_type) {
        out.push_str("    ");
        emit_array_element_release_expr(out, element_type, value);
        out.push_str(";\n");
    }
}

fn emit_array_element_release_expr(out: &mut String, element_type: &ValueType, value: &str) {
    if value_type_needs_release(element_type) {
        out.push_str(&c_release_ident(element_type));
        out.push('(');
        out.push_str(value);
        out.push(')');
    }
}

fn emit_array_element_retain_expr(out: &mut String, element_type: &ValueType, value: &str) {
    if value_type_needs_release(element_type) {
        out.push_str(&c_retain_ident(element_type));
        out.push('(');
        out.push_str(value);
        out.push(')');
    } else {
        out.push_str(value);
    }
}
