use super::*;

pub(super) fn emit_operator_runtime(out: &mut String) {
    out.push_str("static long long nomo_add_i64(long long left, long long right) {\n");
    out.push_str("    if ((right > 0 && left > LLONG_MAX - right) || (right < 0 && left < LLONG_MIN - right)) { nomo_panic(\"signed integer overflow\"); }\n");
    out.push_str("    return left + right;\n");
    out.push_str("}\n\n");
    out.push_str("static long long nomo_sub_i64(long long left, long long right) {\n");
    out.push_str("    if ((right < 0 && left > LLONG_MAX + right) || (right > 0 && left < LLONG_MIN + right)) { nomo_panic(\"signed integer overflow\"); }\n");
    out.push_str("    return left - right;\n");
    out.push_str("}\n\n");
    out.push_str("static long long nomo_mul_i64(long long left, long long right) {\n");
    out.push_str("    if (left == 0 || right == 0) { return 0; }\n");
    out.push_str("    if ((left == -1 && right == LLONG_MIN) || (right == -1 && left == LLONG_MIN)) { nomo_panic(\"signed integer overflow\"); }\n");
    out.push_str("    if (left > 0) {\n");
    out.push_str("        if (right > 0) { if (left > LLONG_MAX / right) { nomo_panic(\"signed integer overflow\"); } }\n");
    out.push_str("        else { if (right < LLONG_MIN / left) { nomo_panic(\"signed integer overflow\"); } }\n");
    out.push_str("    } else {\n");
    out.push_str("        if (right > 0) { if (left < LLONG_MIN / right) { nomo_panic(\"signed integer overflow\"); } }\n");
    out.push_str("        else { if (left < LLONG_MAX / right) { nomo_panic(\"signed integer overflow\"); } }\n");
    out.push_str("    }\n");
    out.push_str("    return left * right;\n");
    out.push_str("}\n\n");
    out.push_str("static long long nomo_div_i64(long long left, long long right) {\n");
    out.push_str("    if (right == 0) { nomo_panic(\"division by zero\"); }\n");
    out.push_str(
        "    if (left == LLONG_MIN && right == -1) { nomo_panic(\"signed integer overflow\"); }\n",
    );
    out.push_str("    return left / right;\n");
    out.push_str("}\n\n");
    out.push_str("static long long nomo_rem_i64(long long left, long long right) {\n");
    out.push_str("    if (right == 0) { nomo_panic(\"division by zero\"); }\n");
    out.push_str(
        "    if (left == LLONG_MIN && right == -1) { nomo_panic(\"signed integer overflow\"); }\n",
    );
    out.push_str("    return left % right;\n");
    out.push_str("}\n\n");
    out.push_str("static int32_t nomo_add_i32(int32_t left, int32_t right) {\n");
    out.push_str("    if ((right > 0 && left > INT32_MAX - right) || (right < 0 && left < INT32_MIN - right)) { nomo_panic(\"signed integer overflow\"); }\n");
    out.push_str("    return left + right;\n");
    out.push_str("}\n\n");
    out.push_str("static int32_t nomo_sub_i32(int32_t left, int32_t right) {\n");
    out.push_str("    if ((right < 0 && left > INT32_MAX + right) || (right > 0 && left < INT32_MIN + right)) { nomo_panic(\"signed integer overflow\"); }\n");
    out.push_str("    return left - right;\n");
    out.push_str("}\n\n");
    out.push_str("static int32_t nomo_mul_i32(int32_t left, int32_t right) {\n");
    out.push_str("    if (left == 0 || right == 0) { return 0; }\n");
    out.push_str("    if ((left == -1 && right == INT32_MIN) || (right == -1 && left == INT32_MIN)) { nomo_panic(\"signed integer overflow\"); }\n");
    out.push_str("    if (left > 0) {\n");
    out.push_str("        if (right > 0) { if (left > INT32_MAX / right) { nomo_panic(\"signed integer overflow\"); } }\n");
    out.push_str("        else { if (right < INT32_MIN / left) { nomo_panic(\"signed integer overflow\"); } }\n");
    out.push_str("    } else {\n");
    out.push_str("        if (right > 0) { if (left < INT32_MIN / right) { nomo_panic(\"signed integer overflow\"); } }\n");
    out.push_str("        else { if (left < INT32_MAX / right) { nomo_panic(\"signed integer overflow\"); } }\n");
    out.push_str("    }\n");
    out.push_str("    return left * right;\n");
    out.push_str("}\n\n");
    out.push_str("static int32_t nomo_div_i32(int32_t left, int32_t right) {\n");
    out.push_str("    if (right == 0) { nomo_panic(\"division by zero\"); }\n");
    out.push_str(
        "    if (left == INT32_MIN && right == -1) { nomo_panic(\"signed integer overflow\"); }\n",
    );
    out.push_str("    return left / right;\n");
    out.push_str("}\n\n");
    out.push_str("static int32_t nomo_rem_i32(int32_t left, int32_t right) {\n");
    out.push_str("    if (right == 0) { nomo_panic(\"division by zero\"); }\n");
    out.push_str(
        "    if (left == INT32_MIN && right == -1) { nomo_panic(\"signed integer overflow\"); }\n",
    );
    out.push_str("    return left % right;\n");
    out.push_str("}\n\n");
    out.push_str("static uint32_t nomo_div_u32(uint32_t left, uint32_t right) {\n");
    out.push_str("    if (right == 0) { nomo_panic(\"division by zero\"); }\n");
    out.push_str("    return left / right;\n");
    out.push_str("}\n\n");
    out.push_str("static uint32_t nomo_rem_u32(uint32_t left, uint32_t right) {\n");
    out.push_str("    if (right == 0) { nomo_panic(\"division by zero\"); }\n");
    out.push_str("    return left % right;\n");
    out.push_str("}\n\n");
    out.push_str("static uint64_t nomo_div_u64(uint64_t left, uint64_t right) {\n");
    out.push_str("    if (right == 0) { nomo_panic(\"division by zero\"); }\n");
    out.push_str("    return left / right;\n");
    out.push_str("}\n\n");
    out.push_str("static uint64_t nomo_rem_u64(uint64_t left, uint64_t right) {\n");
    out.push_str("    if (right == 0) { nomo_panic(\"division by zero\"); }\n");
    out.push_str("    return left % right;\n");
    out.push_str("}\n\n");
    out.push_str("static double nomo_div_f64(double left, double right) {\n");
    out.push_str("    if (right == 0.0) { nomo_panic(\"division by zero\"); }\n");
    out.push_str("    return left / right;\n");
    out.push_str("}\n\n");
    out.push_str("static long long nomo_shl_i64(long long left, uint64_t right) {\n");
    out.push_str(
        "    if (right >= sizeof(left) * CHAR_BIT) { nomo_panic(\"invalid shift amount\"); }\n",
    );
    out.push_str("    return left << right;\n");
    out.push_str("}\n\n");
    out.push_str("static long long nomo_shr_i64(long long left, uint64_t right) {\n");
    out.push_str(
        "    if (right >= sizeof(left) * CHAR_BIT) { nomo_panic(\"invalid shift amount\"); }\n",
    );
    out.push_str("    uint64_t bits = (uint64_t)left;\n");
    out.push_str("    if (right == 0) { return left; }\n");
    out.push_str("    if (left >= 0) { return (long long)(bits >> right); }\n");
    out.push_str("    uint64_t shifted = (bits >> right) | (~UINT64_C(0) << (64U - right));\n");
    out.push_str("    return -1 - (long long)(UINT64_MAX - shifted);\n");
    out.push_str("}\n\n");
    out.push_str("static int32_t nomo_shl_i32(int32_t left, uint64_t right) {\n");
    out.push_str(
        "    if (right >= sizeof(left) * CHAR_BIT) { nomo_panic(\"invalid shift amount\"); }\n",
    );
    out.push_str("    return left << right;\n");
    out.push_str("}\n\n");
    out.push_str("static int32_t nomo_shr_i32(int32_t left, uint64_t right) {\n");
    out.push_str(
        "    if (right >= sizeof(left) * CHAR_BIT) { nomo_panic(\"invalid shift amount\"); }\n",
    );
    out.push_str("    uint32_t bits = (uint32_t)left;\n");
    out.push_str("    if (right == 0) { return left; }\n");
    out.push_str("    if (left >= 0) { return (int32_t)(bits >> right); }\n");
    out.push_str("    uint32_t shifted = (bits >> right) | (~UINT32_C(0) << (32U - right));\n");
    out.push_str("    return -1 - (int32_t)(UINT32_MAX - shifted);\n");
    out.push_str("}\n\n");
    out.push_str("static uint32_t nomo_shl_u32(uint32_t left, uint64_t right) {\n");
    out.push_str(
        "    if (right >= sizeof(left) * CHAR_BIT) { nomo_panic(\"invalid shift amount\"); }\n",
    );
    out.push_str("    return left << right;\n");
    out.push_str("}\n\n");
    out.push_str("static uint32_t nomo_shr_u32(uint32_t left, uint64_t right) {\n");
    out.push_str(
        "    if (right >= sizeof(left) * CHAR_BIT) { nomo_panic(\"invalid shift amount\"); }\n",
    );
    out.push_str("    return left >> right;\n");
    out.push_str("}\n\n");
    out.push_str("static uint64_t nomo_shl_u64(uint64_t left, uint64_t right) {\n");
    out.push_str(
        "    if (right >= sizeof(left) * CHAR_BIT) { nomo_panic(\"invalid shift amount\"); }\n",
    );
    out.push_str("    return left << right;\n");
    out.push_str("}\n\n");
    out.push_str("static uint64_t nomo_shr_u64(uint64_t left, uint64_t right) {\n");
    out.push_str(
        "    if (right >= sizeof(left) * CHAR_BIT) { nomo_panic(\"invalid shift amount\"); }\n",
    );
    out.push_str("    return left >> right;\n");
    out.push_str("}\n\n");
    out.push_str("static long long nomo_wrap_i64(uint64_t bits) {\n");
    out.push_str("    if (bits <= (uint64_t)LLONG_MAX) { return (long long)bits; }\n");
    out.push_str("    return -1 - (long long)(UINT64_MAX - bits);\n");
    out.push_str("}\n\n");
    out.push_str("static int32_t nomo_wrap_i32(uint32_t bits) {\n");
    out.push_str("    if (bits <= (uint32_t)INT32_MAX) { return (int32_t)bits; }\n");
    out.push_str("    return (int32_t)(-1 - (int32_t)(UINT32_MAX - bits));\n");
    out.push_str("}\n\n");
    out.push_str("static long long nomo_num_wrapping_add_i64(long long left, long long right) {\n");
    out.push_str("    return nomo_wrap_i64((uint64_t)left + (uint64_t)right);\n");
    out.push_str("}\n\n");
    out.push_str("static long long nomo_num_wrapping_sub_i64(long long left, long long right) {\n");
    out.push_str("    return nomo_wrap_i64((uint64_t)left - (uint64_t)right);\n");
    out.push_str("}\n\n");
    out.push_str("static long long nomo_num_wrapping_mul_i64(long long left, long long right) {\n");
    out.push_str("    return nomo_wrap_i64((uint64_t)left * (uint64_t)right);\n");
    out.push_str("}\n\n");
    out.push_str("static int32_t nomo_num_wrapping_add_i32(int32_t left, int32_t right) {\n");
    out.push_str("    return nomo_wrap_i32((uint32_t)left + (uint32_t)right);\n");
    out.push_str("}\n\n");
    out.push_str("static int32_t nomo_num_wrapping_sub_i32(int32_t left, int32_t right) {\n");
    out.push_str("    return nomo_wrap_i32((uint32_t)left - (uint32_t)right);\n");
    out.push_str("}\n\n");
    out.push_str("static int32_t nomo_num_wrapping_mul_i32(int32_t left, int32_t right) {\n");
    out.push_str("    return nomo_wrap_i32((uint32_t)left * (uint32_t)right);\n");
    out.push_str("}\n\n");
    out.push_str("static uint32_t nomo_num_wrapping_add_u32(uint32_t left, uint32_t right) {\n");
    out.push_str("    return left + right;\n");
    out.push_str("}\n\n");
    out.push_str("static uint32_t nomo_num_wrapping_sub_u32(uint32_t left, uint32_t right) {\n");
    out.push_str("    return left - right;\n");
    out.push_str("}\n\n");
    out.push_str("static uint32_t nomo_num_wrapping_mul_u32(uint32_t left, uint32_t right) {\n");
    out.push_str("    return left * right;\n");
    out.push_str("}\n\n");
    out.push_str("static uint64_t nomo_num_wrapping_add_u64(uint64_t left, uint64_t right) {\n");
    out.push_str("    return left + right;\n");
    out.push_str("}\n\n");
    out.push_str("static uint64_t nomo_num_wrapping_sub_u64(uint64_t left, uint64_t right) {\n");
    out.push_str("    return left - right;\n");
    out.push_str("}\n\n");
    out.push_str("static uint64_t nomo_num_wrapping_mul_u64(uint64_t left, uint64_t right) {\n");
    out.push_str("    return left * right;\n");
    out.push_str("}\n");
}

pub(super) fn emit_math_runtime(out: &mut String) {
    out.push_str("static int64_t nomo_math_abs_i64(int64_t value) {\n");
    out.push_str("    if (value == INT64_MIN) { nomo_panic(\"integer overflow\"); }\n");
    out.push_str("    return value < 0 ? -value : value;\n");
    out.push_str("}\n\n");
    out.push_str("static int32_t nomo_math_abs_i32(int32_t value) {\n");
    out.push_str("    if (value == INT32_MIN) { nomo_panic(\"integer overflow\"); }\n");
    out.push_str("    return value < 0 ? -value : value;\n");
    out.push_str("}\n\n");
    out.push_str("static uint32_t nomo_math_abs_u32(uint32_t value) {\n");
    out.push_str("    return value;\n");
    out.push_str("}\n\n");
    out.push_str("static uint64_t nomo_math_abs_u64(uint64_t value) {\n");
    out.push_str("    return value;\n");
    out.push_str("}\n\n");
    out.push_str("static double nomo_math_abs_f64(double value) {\n");
    out.push_str("    return fabs(value);\n");
    out.push_str("}\n\n");
    out.push_str("static int64_t nomo_math_min_i64(int64_t left, int64_t right) {\n");
    out.push_str("    return left < right ? left : right;\n");
    out.push_str("}\n\n");
    out.push_str("static int32_t nomo_math_min_i32(int32_t left, int32_t right) {\n");
    out.push_str("    return left < right ? left : right;\n");
    out.push_str("}\n\n");
    out.push_str("static uint32_t nomo_math_min_u32(uint32_t left, uint32_t right) {\n");
    out.push_str("    return left < right ? left : right;\n");
    out.push_str("}\n\n");
    out.push_str("static uint64_t nomo_math_min_u64(uint64_t left, uint64_t right) {\n");
    out.push_str("    return left < right ? left : right;\n");
    out.push_str("}\n\n");
    out.push_str("static double nomo_math_min_f64(double left, double right) {\n");
    out.push_str("    return left < right ? left : right;\n");
    out.push_str("}\n\n");
    out.push_str("static int64_t nomo_math_max_i64(int64_t left, int64_t right) {\n");
    out.push_str("    return left > right ? left : right;\n");
    out.push_str("}\n\n");
    out.push_str("static int32_t nomo_math_max_i32(int32_t left, int32_t right) {\n");
    out.push_str("    return left > right ? left : right;\n");
    out.push_str("}\n\n");
    out.push_str("static uint32_t nomo_math_max_u32(uint32_t left, uint32_t right) {\n");
    out.push_str("    return left > right ? left : right;\n");
    out.push_str("}\n\n");
    out.push_str("static uint64_t nomo_math_max_u64(uint64_t left, uint64_t right) {\n");
    out.push_str("    return left > right ? left : right;\n");
    out.push_str("}\n\n");
    out.push_str("static double nomo_math_max_f64(double left, double right) {\n");
    out.push_str("    return left > right ? left : right;\n");
    out.push_str("}\n");
}

pub(super) fn emit_string_runtime(out: &mut String) {
    out.push_str("typedef struct nomo_string {\n");
    out.push_str("    const char *data;\n");
    out.push_str("    size_t *refcount;\n");
    out.push_str("} nomo_string;\n\n");
    out.push_str("static nomo_string nomo_string_literal(const char *data) {\n");
    out.push_str("    return (nomo_string){.data = data, .refcount = NULL};\n");
    out.push_str("}\n\n");
    out.push_str("static nomo_string nomo_string_owned(char *data) {\n");
    out.push_str("    size_t *refcount = (size_t *)malloc(sizeof(size_t));\n");
    out.push_str("    if (refcount == NULL) {\n");
    out.push_str("        free(data);\n");
    out.push_str("        nomo_panic(\"out of memory\");\n");
    out.push_str("    }\n");
    out.push_str("    *refcount = 1;\n");
    out.push_str("    return (nomo_string){.data = data, .refcount = refcount};\n");
    out.push_str("}\n\n");
    out.push_str("static nomo_string nomo_string_from_cstr(const char *value) {\n");
    out.push_str("    size_t len = strlen(value);\n");
    out.push_str("    char *data = (char *)malloc(len + 1);\n");
    out.push_str("    if (data == NULL) { nomo_panic(\"out of memory\"); }\n");
    out.push_str("    memcpy(data, value, len + 1);\n");
    out.push_str("    return nomo_string_owned(data);\n");
    out.push_str("}\n\n");
    out.push_str(
        "static nomo_string nomo_string_from_slice(const char *data, size_t start, size_t len) {\n",
    );
    out.push_str("    char *out = (char *)malloc(len + 1);\n");
    out.push_str("    if (out == NULL) { nomo_panic(\"out of memory\"); }\n");
    out.push_str("    memcpy(out, data + start, len);\n");
    out.push_str("    out[len] = '\\0';\n");
    out.push_str("    return nomo_string_owned(out);\n");
    out.push_str("}\n\n");
    out.push_str("static nomo_string nomo_string_retain(nomo_string value) {\n");
    out.push_str("    if (value.refcount != NULL) { *value.refcount += 1; }\n");
    out.push_str("    return value;\n");
    out.push_str("}\n\n");
    out.push_str("static void nomo_string_release(nomo_string value) {\n");
    out.push_str("    if (value.refcount == NULL) { return; }\n");
    out.push_str("    *value.refcount -= 1;\n");
    out.push_str("    if (*value.refcount != 0) { return; }\n");
    out.push_str("    free((char *)value.data);\n");
    out.push_str("    free(value.refcount);\n");
    out.push_str("}\n\n");
    out.push_str("static nomo_string nomo_string_concat(nomo_string left, nomo_string right) {\n");
    out.push_str("    size_t left_len = strlen(left.data);\n");
    out.push_str("    size_t right_len = strlen(right.data);\n");
    out.push_str("    char *out = (char *)malloc(left_len + right_len + 1);\n");
    out.push_str("    if (out == NULL) {\n");
    out.push_str("        nomo_panic(\"out of memory\");\n");
    out.push_str("    }\n");
    out.push_str("    memcpy(out, left.data, left_len);\n");
    out.push_str("    memcpy(out + left_len, right.data, right_len + 1);\n");
    out.push_str("    return nomo_string_owned(out);\n");
    out.push_str("}\n");
    out.push_str("\nstatic int nomo_string_equal(nomo_string left, nomo_string right) {\n");
    out.push_str("    return strcmp(left.data, right.data) == 0;\n");
    out.push_str("}\n");
    out.push_str("\nstatic int nomo_string_is_empty(nomo_string value) {\n");
    out.push_str("    return value.data[0] == '\\0';\n");
    out.push_str("}\n");
    out.push_str("\nstatic int nomo_string_contains(nomo_string value, nomo_string needle) {\n");
    out.push_str("    return strstr(value.data, needle.data) != NULL;\n");
    out.push_str("}\n");
    out.push_str("\nstatic int nomo_string_starts_with(nomo_string value, nomo_string prefix) {\n");
    out.push_str("    size_t prefix_len = strlen(prefix.data);\n");
    out.push_str("    return strncmp(value.data, prefix.data, prefix_len) == 0;\n");
    out.push_str("}\n");
    out.push_str("\nstatic int nomo_string_ends_with(nomo_string value, nomo_string suffix) {\n");
    out.push_str("    size_t value_len = strlen(value.data);\n");
    out.push_str("    size_t suffix_len = strlen(suffix.data);\n");
    out.push_str("    if (suffix_len > value_len) { return 0; }\n");
    out.push_str(
        "    return memcmp(value.data + value_len - suffix_len, suffix.data, suffix_len) == 0;\n",
    );
    out.push_str("}\n");
    out.push_str("\nstatic nomo_string nomo_string_trim(nomo_string value) {\n");
    out.push_str("    size_t start = 0;\n");
    out.push_str("    size_t end = strlen(value.data);\n");
    out.push_str(
        "    while (start < end && isspace((unsigned char)value.data[start])) { start += 1; }\n",
    );
    out.push_str(
        "    while (end > start && isspace((unsigned char)value.data[end - 1])) { end -= 1; }\n",
    );
    out.push_str("    return nomo_string_from_slice(value.data, start, end - start);\n");
    out.push_str("}\n");
    out.push_str("\nstatic nomo_string nomo_string_to_lower(nomo_string value) {\n");
    out.push_str("    size_t len = strlen(value.data);\n");
    out.push_str("    char *out = (char *)malloc(len + 1);\n");
    out.push_str("    if (out == NULL) { nomo_panic(\"out of memory\"); }\n");
    out.push_str("    for (size_t i = 0; i < len; i += 1) { out[i] = (char)tolower((unsigned char)value.data[i]); }\n");
    out.push_str("    out[len] = '\\0';\n");
    out.push_str("    return nomo_string_owned(out);\n");
    out.push_str("}\n");
    out.push_str("\nstatic nomo_string nomo_string_to_upper(nomo_string value) {\n");
    out.push_str("    size_t len = strlen(value.data);\n");
    out.push_str("    char *out = (char *)malloc(len + 1);\n");
    out.push_str("    if (out == NULL) { nomo_panic(\"out of memory\"); }\n");
    out.push_str("    for (size_t i = 0; i < len; i += 1) { out[i] = (char)toupper((unsigned char)value.data[i]); }\n");
    out.push_str("    out[len] = '\\0';\n");
    out.push_str("    return nomo_string_owned(out);\n");
    out.push_str("}\n");
    out.push_str("\nstatic int nomo_char_is_digit(uint32_t value) {\n");
    out.push_str("    return value <= 127 && isdigit((unsigned char)value) != 0;\n");
    out.push_str("}\n");
    out.push_str("\nstatic int nomo_char_is_alpha(uint32_t value) {\n");
    out.push_str("    return value <= 127 && isalpha((unsigned char)value) != 0;\n");
    out.push_str("}\n");
    out.push_str("\nstatic int nomo_char_is_whitespace(uint32_t value) {\n");
    out.push_str("    return value <= 127 && isspace((unsigned char)value) != 0;\n");
    out.push_str("}\n");
    out.push_str("\nstatic nomo_string nomo_char_to_string(uint32_t value) {\n");
    out.push_str("    char *out = (char *)malloc(5);\n");
    out.push_str("    if (out == NULL) { nomo_panic(\"out of memory\"); }\n");
    out.push_str("    if (value <= 0x7F) {\n");
    out.push_str("        out[0] = (char)value;\n");
    out.push_str("        out[1] = '\\0';\n");
    out.push_str("    } else if (value <= 0x7FF) {\n");
    out.push_str("        out[0] = (char)(0xC0 | (value >> 6));\n");
    out.push_str("        out[1] = (char)(0x80 | (value & 0x3F));\n");
    out.push_str("        out[2] = '\\0';\n");
    out.push_str("    } else if (value <= 0xFFFF) {\n");
    out.push_str("        out[0] = (char)(0xE0 | (value >> 12));\n");
    out.push_str("        out[1] = (char)(0x80 | ((value >> 6) & 0x3F));\n");
    out.push_str("        out[2] = (char)(0x80 | (value & 0x3F));\n");
    out.push_str("        out[3] = '\\0';\n");
    out.push_str("    } else if (value <= 0x10FFFF) {\n");
    out.push_str("        out[0] = (char)(0xF0 | (value >> 18));\n");
    out.push_str("        out[1] = (char)(0x80 | ((value >> 12) & 0x3F));\n");
    out.push_str("        out[2] = (char)(0x80 | ((value >> 6) & 0x3F));\n");
    out.push_str("        out[3] = (char)(0x80 | (value & 0x3F));\n");
    out.push_str("        out[4] = '\\0';\n");
    out.push_str("    } else {\n");
    out.push_str("        out[0] = '?';\n");
    out.push_str("        out[1] = '\\0';\n");
    out.push_str("    }\n");
    out.push_str("    return nomo_string_owned(out);\n");
    out.push_str("}\n");
    out.push_str("\nstatic nomo_string nomo_os_platform(void) {\n");
    out.push_str("#if defined(_WIN32)\n");
    out.push_str("    return nomo_string_literal(\"windows\");\n");
    out.push_str("#elif defined(__APPLE__)\n");
    out.push_str("    return nomo_string_literal(\"macos\");\n");
    out.push_str("#elif defined(__linux__)\n");
    out.push_str("    return nomo_string_literal(\"linux\");\n");
    out.push_str("#elif defined(__FreeBSD__)\n");
    out.push_str("    return nomo_string_literal(\"freebsd\");\n");
    out.push_str("#else\n");
    out.push_str("    return nomo_string_literal(\"unknown\");\n");
    out.push_str("#endif\n");
    out.push_str("}\n");
    out.push_str("\nstatic nomo_string nomo_os_arch(void) {\n");
    out.push_str("#if defined(__aarch64__) || defined(_M_ARM64)\n");
    out.push_str("    return nomo_string_literal(\"aarch64\");\n");
    out.push_str("#elif defined(__x86_64__) || defined(_M_X64)\n");
    out.push_str("    return nomo_string_literal(\"x86_64\");\n");
    out.push_str("#elif defined(__i386__) || defined(_M_IX86)\n");
    out.push_str("    return nomo_string_literal(\"x86\");\n");
    out.push_str("#elif defined(__arm__) || defined(_M_ARM)\n");
    out.push_str("    return nomo_string_literal(\"arm\");\n");
    out.push_str("#else\n");
    out.push_str("    return nomo_string_literal(\"unknown\");\n");
    out.push_str("#endif\n");
    out.push_str("}\n");
    out.push_str("\nstatic nomo_string nomo_os_path_separator(void) {\n");
    out.push_str("#if defined(_WIN32)\n");
    out.push_str("    return nomo_string_literal(\"\\\\\");\n");
    out.push_str("#else\n");
    out.push_str("    return nomo_string_literal(\"/\");\n");
    out.push_str("#endif\n");
    out.push_str("}\n");
    out.push_str("\nstatic nomo_string nomo_os_line_ending(void) {\n");
    out.push_str("#if defined(_WIN32)\n");
    out.push_str("    return nomo_string_literal(\"\\r\\n\");\n");
    out.push_str("#else\n");
    out.push_str("    return nomo_string_literal(\"\\n\");\n");
    out.push_str("#endif\n");
    out.push_str("}\n");
    out.push_str("\nstatic int64_t nomo_time_now_millis(void) {\n");
    out.push_str("#if defined(_WIN32)\n");
    out.push_str("    FILETIME ft;\n");
    out.push_str("    ULARGE_INTEGER value;\n");
    out.push_str("    GetSystemTimeAsFileTime(&ft);\n");
    out.push_str("    value.LowPart = ft.dwLowDateTime;\n");
    out.push_str("    value.HighPart = ft.dwHighDateTime;\n");
    out.push_str("    return (int64_t)((value.QuadPart - 116444736000000000ULL) / 10000ULL);\n");
    out.push_str("#else\n");
    out.push_str("    struct timeval tv;\n");
    out.push_str(
        "    if (gettimeofday(&tv, NULL) != 0) { nomo_panic(\"time.now_millis failed\"); }\n",
    );
    out.push_str("    return ((int64_t)tv.tv_sec * 1000) + ((int64_t)tv.tv_usec / 1000);\n");
    out.push_str("#endif\n");
    out.push_str("}\n");
    out.push_str("\nstatic int64_t nomo_time_monotonic_millis(void) {\n");
    out.push_str("#if defined(_WIN32)\n");
    out.push_str("    return (int64_t)GetTickCount64();\n");
    out.push_str("#else\n");
    out.push_str("    struct timespec ts;\n");
    out.push_str("    if (clock_gettime(CLOCK_MONOTONIC, &ts) != 0) { nomo_panic(\"time.monotonic_millis failed\"); }\n");
    out.push_str("    return ((int64_t)ts.tv_sec * 1000) + ((int64_t)ts.tv_nsec / 1000000);\n");
    out.push_str("#endif\n");
    out.push_str("}\n");
    out.push_str("\nstatic void nomo_time_sleep_millis(int64_t duration) {\n");
    out.push_str("    if (duration < 0) { nomo_panic(\"time.sleep_millis duration must be non-negative\"); }\n");
    out.push_str("#if defined(_WIN32)\n");
    out.push_str("    Sleep((DWORD)duration);\n");
    out.push_str("#else\n");
    out.push_str("    struct timespec request;\n");
    out.push_str("    request.tv_sec = (time_t)(duration / 1000);\n");
    out.push_str("    request.tv_nsec = (long)((duration % 1000) * 1000000);\n");
    out.push_str("    while (nanosleep(&request, &request) != 0) {\n");
    out.push_str("        if (errno != EINTR) { nomo_panic(\"time.sleep_millis failed\"); }\n");
    out.push_str("    }\n");
    out.push_str("#endif\n");
    out.push_str("}\n");
    out.push_str("\nstatic int64_t nomo_time_duration_seconds_to_millis(int64_t seconds) {\n");
    out.push_str("    if (seconds > INT64_MAX / 1000 || seconds < INT64_MIN / 1000) { nomo_panic(\"time.duration_seconds overflow\"); }\n");
    out.push_str("    return seconds * 1000;\n");
    out.push_str("}\n");
    out.push_str("\nstatic nomo_string nomo_time_format_duration_millis(int64_t millis) {\n");
    out.push_str("    char buffer[64];\n");
    out.push_str("    snprintf(buffer, sizeof(buffer), \"%\" PRId64 \"ms\", millis);\n");
    out.push_str("    return nomo_string_from_cstr(buffer);\n");
    out.push_str("}\n");
    out.push_str("\nstatic nomo_string nomo_num_i64_to_string(int64_t value) {\n");
    out.push_str("    char buffer[64];\n");
    out.push_str("    snprintf(buffer, sizeof(buffer), \"%\" PRId64, value);\n");
    out.push_str("    return nomo_string_from_cstr(buffer);\n");
    out.push_str("}\n");
    out.push_str("\nstatic nomo_string nomo_num_i32_to_string(int32_t value) {\n");
    out.push_str("    char buffer[32];\n");
    out.push_str("    snprintf(buffer, sizeof(buffer), \"%\" PRId32, value);\n");
    out.push_str("    return nomo_string_from_cstr(buffer);\n");
    out.push_str("}\n");
    out.push_str("\nstatic nomo_string nomo_num_u32_to_string(uint32_t value) {\n");
    out.push_str("    char buffer[32];\n");
    out.push_str("    snprintf(buffer, sizeof(buffer), \"%\" PRIu32, value);\n");
    out.push_str("    return nomo_string_from_cstr(buffer);\n");
    out.push_str("}\n");
    out.push_str("\nstatic nomo_string nomo_num_u64_to_string(uint64_t value) {\n");
    out.push_str("    char buffer[64];\n");
    out.push_str("    snprintf(buffer, sizeof(buffer), \"%\" PRIu64, value);\n");
    out.push_str("    return nomo_string_from_cstr(buffer);\n");
    out.push_str("}\n");
    out.push_str("\nstatic nomo_string nomo_num_f64_to_string(double value) {\n");
    out.push_str("    char buffer[128];\n");
    out.push_str("    snprintf(buffer, sizeof(buffer), \"%.17g\", value);\n");
    out.push_str("    return nomo_string_from_cstr(buffer);\n");
    out.push_str("}\n");
    emit_path_runtime(out);
}

pub(super) fn emit_log_enabled_helper(out: &mut String) {
    out.push_str("static int32_t nomo_log_level_value(const char *level) {\n");
    out.push_str("    if (strcmp(level, \"debug\") == 0) { return 0; }\n");
    out.push_str("    if (strcmp(level, \"info\") == 0) { return 1; }\n");
    out.push_str(
        "    if (strcmp(level, \"warn\") == 0 || strcmp(level, \"warning\") == 0) { return 2; }\n",
    );
    out.push_str("    if (strcmp(level, \"error\") == 0) { return 3; }\n");
    out.push_str("    if (strcmp(level, \"off\") == 0) { return 4; }\n");
    out.push_str("    return 1;\n");
    out.push_str("}\n\n");
    out.push_str("static int32_t nomo_log_enabled(nomo_string level) {\n");
    out.push_str("    const char *filter = getenv(\"NOMO_LOG\");\n");
    out.push_str("    int32_t threshold = filter == NULL ? 1 : nomo_log_level_value(filter);\n");
    out.push_str("    int32_t current = nomo_log_level_value(level.data);\n");
    out.push_str("    return threshold < 4 && current >= threshold;\n");
    out.push_str("}\n");
}

pub(super) fn emit_hash_helpers(out: &mut String) {
    let hash_state = c_type(&ValueType::Struct("HashState".to_string(), Vec::new()));
    let value_field = c_member_ident("value");
    out.push_str("static const uint64_t NOMO_HASH_OFFSET = UINT64_C(14695981039346656037);\n");
    out.push_str("static const uint64_t NOMO_HASH_PRIME = UINT64_C(1099511628211);\n\n");
    out.push_str("static uint64_t nomo_hash_write_cstr(uint64_t state, const char *data) {\n");
    out.push_str("    const unsigned char *bytes = (const unsigned char *)data;\n");
    out.push_str("    while (*bytes != '\\0') {\n");
    out.push_str("        state ^= (uint64_t)(*bytes);\n");
    out.push_str("        state *= NOMO_HASH_PRIME;\n");
    out.push_str("        bytes += 1;\n");
    out.push_str("    }\n");
    out.push_str("    return state;\n");
    out.push_str("}\n\n");
    out.push_str(
        "static uint64_t nomo_hash_write_array_u32(uint64_t state, nomo_array_u32 data) {\n",
    );
    out.push_str("    for (size_t i = 0; i < data.len; i += 1) {\n");
    out.push_str("        state ^= (uint64_t)(data.data[i] & 0xffU);\n");
    out.push_str("        state *= NOMO_HASH_PRIME;\n");
    out.push_str("    }\n");
    out.push_str("    return state;\n");
    out.push_str("}\n\n");
    out.push_str("static ");
    out.push_str(&hash_state);
    out.push_str(" nomo_hash_new(void) {\n");
    out.push_str("    return (");
    out.push_str(&hash_state);
    out.push_str("){.");
    out.push_str(&value_field);
    out.push_str(" = NOMO_HASH_OFFSET};\n");
    out.push_str("}\n\n");
    out.push_str("static uint64_t nomo_hash_string(nomo_string value) {\n");
    out.push_str("    return nomo_hash_write_cstr(NOMO_HASH_OFFSET, value.data);\n");
    out.push_str("}\n\n");
    out.push_str("static uint64_t nomo_hash_bytes(nomo_array_u32 value) {\n");
    out.push_str("    return nomo_hash_write_array_u32(NOMO_HASH_OFFSET, value);\n");
    out.push_str("}\n\n");
    out.push_str("static ");
    out.push_str(&hash_state);
    out.push_str(" nomo_hash_write_string(");
    out.push_str(&hash_state);
    out.push_str(" state, nomo_string value) {\n");
    out.push_str("    return (");
    out.push_str(&hash_state);
    out.push_str("){.");
    out.push_str(&value_field);
    out.push_str(" = nomo_hash_write_cstr(state.");
    out.push_str(&value_field);
    out.push_str(", value.data)};\n");
    out.push_str("}\n\n");
    out.push_str("static ");
    out.push_str(&hash_state);
    out.push_str(" nomo_hash_write_bytes(");
    out.push_str(&hash_state);
    out.push_str(" state, nomo_array_u32 value) {\n");
    out.push_str("    return (");
    out.push_str(&hash_state);
    out.push_str("){.");
    out.push_str(&value_field);
    out.push_str(" = nomo_hash_write_array_u32(state.");
    out.push_str(&value_field);
    out.push_str(", value)};\n");
    out.push_str("}\n\n");
    out.push_str("static uint64_t nomo_hash_finish(");
    out.push_str(&hash_state);
    out.push_str(" state) {\n");
    out.push_str("    return state.");
    out.push_str(&value_field);
    out.push_str(";\n");
    out.push_str("}\n");
}
