manifest-version = 2

[workspace]
members = ["apps/*", "packages/*"]
default-members = ["apps/app"]

[workspace.package]
namespace = "examples"
edition = "2026"

[workspace.dependencies]
util = { path = "packages/util" }
