use super::*;

pub(super) fn emit_hash_helpers(out: &mut String) {
    let hash_state = c_type(&ValueType::Struct("HashState".to_string(), Vec::new()));
    let value_field = c_member_ident("value");
    out.push_str("static const uint64_t NOMO_HASH_OFFSET = UINT64_C(14695981039346656037);\n");
    out.push_str("static const uint64_t NOMO_HASH_PRIME = UINT64_C(1099511628211);\n\n");
    out.push_str("static uint64_t nomo_hash_write_cstr(uint64_t state, const char *data) {\n");
    out.push_str("    const unsigned char *bytes = (const unsigned char *)data;\n");
    out.push_str("    while (*bytes != '\\0') {\n");
    out.push_str("        state ^= (uint64_t)(*bytes);\n");
    out.push_str("        state *= NOMO_HASH_PRIME;\n");
    out.push_str("        bytes += 1;\n");
    out.push_str("    }\n");
    out.push_str("    return state;\n");
    out.push_str("}\n\n");
    out.push_str(
        "static uint64_t nomo_hash_write_array_u32(uint64_t state, nomo_array_u32 data) {\n",
    );
    out.push_str("    for (size_t i = 0; i < data.len; i += 1) {\n");
    out.push_str("        state ^= (uint64_t)(data.data[i] & 0xffU);\n");
    out.push_str("        state *= NOMO_HASH_PRIME;\n");
    out.push_str("    }\n");
    out.push_str("    return state;\n");
    out.push_str("}\n\n");
    out.push_str("static ");
    out.push_str(&hash_state);
    out.push_str(" nomo_hash_new(void) {\n");
    out.push_str("    return (");
    out.push_str(&hash_state);
    out.push_str("){.");
    out.push_str(&value_field);
    out.push_str(" = NOMO_HASH_OFFSET};\n");
    out.push_str("}\n\n");
    out.push_str("static uint64_t nomo_hash_string(nomo_string value) {\n");
    out.push_str("    return nomo_hash_write_cstr(NOMO_HASH_OFFSET, value.data);\n");
    out.push_str("}\n\n");
    out.push_str("static uint64_t nomo_hash_bytes(nomo_array_u32 value) {\n");
    out.push_str("    return nomo_hash_write_array_u32(NOMO_HASH_OFFSET, value);\n");
    out.push_str("}\n\n");
    out.push_str("static ");
    out.push_str(&hash_state);
    out.push_str(" nomo_hash_write_string(");
    out.push_str(&hash_state);
    out.push_str(" state, nomo_string value) {\n");
    out.push_str("    return (");
    out.push_str(&hash_state);
    out.push_str("){.");
    out.push_str(&value_field);
    out.push_str(" = nomo_hash_write_cstr(state.");
    out.push_str(&value_field);
    out.push_str(", value.data)};\n");
    out.push_str("}\n\n");
    out.push_str("static ");
    out.push_str(&hash_state);
    out.push_str(" nomo_hash_write_bytes(");
    out.push_str(&hash_state);
    out.push_str(" state, nomo_array_u32 value) {\n");
    out.push_str("    return (");
    out.push_str(&hash_state);
    out.push_str("){.");
    out.push_str(&value_field);
    out.push_str(" = nomo_hash_write_array_u32(state.");
    out.push_str(&value_field);
    out.push_str(", value)};\n");
    out.push_str("}\n\n");
    out.push_str("static uint64_t nomo_hash_finish(");
    out.push_str(&hash_state);
    out.push_str(" state) {\n");
    out.push_str("    return state.");
    out.push_str(&value_field);
    out.push_str(";\n");
    out.push_str("}\n");
}
